// File: mux32bit3to1.v
// Generated by MyHDL 0.9.0
// Date: Sun Apr  8 18:57:20 2018


`timescale 1ns/10ps

module mux32bit3to1 (
    ctrl_line,
    data1,
    mem_rd,
    wb_rd,
    out
);
// 3:1 Mux for forwarding results from 2 cycles ago
// :param ctrl: two bit input selector from fwd_unit
// :param data1: rs data received from id_ex 0
// :param mem_rd: rd from the previous cycle, received from ex_mem 01
// :param wb_rd: rd from two cycles ago, received from wb_mux 10
// :param output: Output for rs/op1.  Sent to ALU
// :return: module logic

input [1:0] ctrl_line;
input signed [31:0] data1;
input signed [31:0] mem_rd;
input signed [31:0] wb_rd;
output [31:0] out;
reg signed [31:0] out;






always @(mem_rd, data1, wb_rd, ctrl_line) begin: MUX32BIT3TO1_LOGIC
    case (ctrl_line)
        'h2: begin
            out = wb_rd;
        end
        'h1: begin
            out = mem_rd;
        end
        'h0: begin
            out = data1;
        end
    endcase
end

endmodule
