// File: pc_adder.v
// Generated by MyHDL 0.9.0
// Date: Mon Apr  2 21:51:19 2018


`timescale 1ns/10ps

module pc_adder (
    cur_pc,
    next_pc
);


input [31:0] cur_pc;
output [31:0] next_pc;
wire [31:0] next_pc;







assign next_pc = (cur_pc + 4);

endmodule
