// File: pc_mux_a.v
// Generated by MyHDL 0.9.0
// Date: Sun Apr  1 22:19:15 2018


`timescale 1ns/10ps

module pc_mux_a (
    pc_src,
    imm_jmp_addr,
    nxt_pc,
    nxt_inst
);
// PC Mux A
// :param pc_src: Which instruction to use, 0 for nxt_pc, 1, for imm_jmp_addr.
// :param imm_jmp_addr: a new PC value from the EX/MEM register
// :param nxt_pc: sequential next PC from pc_adder
// :param nxt_inst: actual next instruction address to pc_mux_b
// :return: generator logic

input [0:0] pc_src;
input [31:0] imm_jmp_addr;
input [31:0] nxt_pc;
output [31:0] nxt_inst;
reg [31:0] nxt_inst;






always @(nxt_pc, pc_src, imm_jmp_addr) begin: PC_MUX_A_LOGIC
    if ((pc_src == 1)) begin
        nxt_inst = imm_jmp_addr;
    end
    else begin
        nxt_inst = nxt_pc;
    end
end

endmodule
