// File: pc_mux_c.v
// Generated by MyHDL 0.9.0
// Date: Mon Apr  2 21:51:16 2018


`timescale 1ns/10ps

module pc_mux_c (
    pc_write,
    cur_pc,
    zero,
    next_pc
);


input pc_write;
input [31:0] cur_pc;
input zero;
output [31:0] next_pc;
reg [31:0] next_pc;






always @(cur_pc, zero, pc_write) begin: PC_MUX_C_LOGIC
    if ((pc_write == 1)) begin
        next_pc = zero;
    end
    else begin
        next_pc = cur_pc;
    end
end

endmodule
