// File: pc_mux_b.v
// Generated by MyHDL 0.9.0
// Date: Mon Apr  2 21:51:13 2018


`timescale 1ns/10ps

module pc_mux_b (
    jmp_ctrl,
    next_inst_address,
    jump_address,
    next_address
);


input jmp_ctrl;
input [31:0] next_inst_address;
input [31:0] jump_address;
output [31:0] next_address;
reg [31:0] next_address;






always @(jump_address, next_inst_address, jmp_ctrl) begin: PC_MUX_B_LOGIC
    if ((jmp_ctrl == 1)) begin
        next_address = jump_address;
    end
    else begin
        next_address = next_inst_address;
    end
end

endmodule
