// File: program_counter.v
// Generated by MyHDL 0.9.0
// Date: Tue Apr  3 22:07:14 2018


`timescale 1ns/10ps

module program_counter (
    clock,
    pc_write,
    nxt_inst,
    cur_pc
);


input clock;
input pc_write;
input [31:0] nxt_inst;
output [31:0] cur_pc;
reg [31:0] cur_pc;






always @(posedge clock) begin: PROGRAM_COUNTER_SEQ_LOGIC
    reg [32-1:0] pc_reg;
    if ((pc_write == 0)) begin
        cur_pc <= nxt_inst;
        pc_reg = nxt_inst;
    end
end

endmodule
