// File: program_counter.v
// Generated by MyHDL 0.9.0
// Date: Mon Apr  2 21:51:24 2018


`timescale 1ns/10ps

module program_counter (
    clock,
    nxt_inst,
    cur_pc
);


input clock;
input [31:0] nxt_inst;
output [31:0] cur_pc;
reg [31:0] cur_pc;






always @(posedge clock) begin: PROGRAM_COUNTER_SEQ_LOGIC
    cur_pc <= nxt_inst;
end

endmodule
