settings = {
    'PERIOD': 10,
    'DEFAULT_TEST_LENGTH': 2000,
    # EXCLUSIVE
    'UNSIGNED_MAX_VALUE': 2 ** 32,
    # EXCLUSIVE
    'SIGNED_MAX_VALUE': 2 ** 31,
    'SIGNED_MIN_VALUE': -2 ** 31,
    '16_SIGNED_MIN_VALUE': -1 * 2**15,
    # EXCLUSIVE
    '16_SIGNED_MAX_VALUE': 2**15,
    'MEMORY_WIDTH': 20,
    'WIDTH': 32,
    'ACTIVE_LOW': 0,
    'INACTIVE_HIGH': 1,
    'ALU_CODE_SIZE': 4
}
